# Generated by Django 6.0.4 on 2026-04-28 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('task_count', models.IntegerField()),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recurence', models.BooleanField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dead_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_count', models.IntegerField()),
                ('progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'folders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField()),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'testik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestikTwo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'testik_two',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
