# Generated by Django 6.0.4 on 2026-05-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testik',
        ),
        migrations.DeleteModel(
            name='TestikTwo',
        ),
    ]
