# Generated by Django 6.0.4 on 2026-06-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_testik_delete_testiktwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeadLines',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
