/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as AccRouteImport } from './routes/acc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoCreateFolderRouteImport } from './routes/todo.create-folder'
import { Route as TodoIdRouteImport } from './routes/todo.$id'
import { Route as AccSing_inRouteImport } from './routes/acc.sing_in'
import { Route as AccRegistrationRouteImport } from './routes/acc.registration'
import { Route as TodoIdCreateTaskRouteImport } from './routes/todo.$id.create-task'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccRoute = AccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoCreateFolderRoute = TodoCreateFolderRouteImport.update({
  id: '/create-folder',
  path: '/create-folder',
  getParentRoute: () => TodoRoute,
} as any)
const TodoIdRoute = TodoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TodoRoute,
} as any)
const AccSing_inRoute = AccSing_inRouteImport.update({
  id: '/sing_in',
  path: '/sing_in',
  getParentRoute: () => AccRoute,
} as any)
const AccRegistrationRoute = AccRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AccRoute,
} as any)
const TodoIdCreateTaskRoute = TodoIdCreateTaskRouteImport.update({
  id: '/create-task',
  path: '/create-task',
  getParentRoute: () => TodoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acc': typeof AccRouteWithChildren
  '/todo': typeof TodoRouteWithChildren
  '/acc/registration': typeof AccRegistrationRoute
  '/acc/sing_in': typeof AccSing_inRoute
  '/todo/$id': typeof TodoIdRouteWithChildren
  '/todo/create-folder': typeof TodoCreateFolderRoute
  '/todo/$id/create-task': typeof TodoIdCreateTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acc': typeof AccRouteWithChildren
  '/todo': typeof TodoRouteWithChildren
  '/acc/registration': typeof AccRegistrationRoute
  '/acc/sing_in': typeof AccSing_inRoute
  '/todo/$id': typeof TodoIdRouteWithChildren
  '/todo/create-folder': typeof TodoCreateFolderRoute
  '/todo/$id/create-task': typeof TodoIdCreateTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acc': typeof AccRouteWithChildren
  '/todo': typeof TodoRouteWithChildren
  '/acc/registration': typeof AccRegistrationRoute
  '/acc/sing_in': typeof AccSing_inRoute
  '/todo/$id': typeof TodoIdRouteWithChildren
  '/todo/create-folder': typeof TodoCreateFolderRoute
  '/todo/$id/create-task': typeof TodoIdCreateTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acc'
    | '/todo'
    | '/acc/registration'
    | '/acc/sing_in'
    | '/todo/$id'
    | '/todo/create-folder'
    | '/todo/$id/create-task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acc'
    | '/todo'
    | '/acc/registration'
    | '/acc/sing_in'
    | '/todo/$id'
    | '/todo/create-folder'
    | '/todo/$id/create-task'
  id:
    | '__root__'
    | '/'
    | '/acc'
    | '/todo'
    | '/acc/registration'
    | '/acc/sing_in'
    | '/todo/$id'
    | '/todo/create-folder'
    | '/todo/$id/create-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccRoute: typeof AccRouteWithChildren
  TodoRoute: typeof TodoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc': {
      id: '/acc'
      path: '/acc'
      fullPath: '/acc'
      preLoaderRoute: typeof AccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/create-folder': {
      id: '/todo/create-folder'
      path: '/create-folder'
      fullPath: '/todo/create-folder'
      preLoaderRoute: typeof TodoCreateFolderRouteImport
      parentRoute: typeof TodoRoute
    }
    '/todo/$id': {
      id: '/todo/$id'
      path: '/$id'
      fullPath: '/todo/$id'
      preLoaderRoute: typeof TodoIdRouteImport
      parentRoute: typeof TodoRoute
    }
    '/acc/sing_in': {
      id: '/acc/sing_in'
      path: '/sing_in'
      fullPath: '/acc/sing_in'
      preLoaderRoute: typeof AccSing_inRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/registration': {
      id: '/acc/registration'
      path: '/registration'
      fullPath: '/acc/registration'
      preLoaderRoute: typeof AccRegistrationRouteImport
      parentRoute: typeof AccRoute
    }
    '/todo/$id/create-task': {
      id: '/todo/$id/create-task'
      path: '/create-task'
      fullPath: '/todo/$id/create-task'
      preLoaderRoute: typeof TodoIdCreateTaskRouteImport
      parentRoute: typeof TodoIdRoute
    }
  }
}

interface AccRouteChildren {
  AccRegistrationRoute: typeof AccRegistrationRoute
  AccSing_inRoute: typeof AccSing_inRoute
}

const AccRouteChildren: AccRouteChildren = {
  AccRegistrationRoute: AccRegistrationRoute,
  AccSing_inRoute: AccSing_inRoute,
}

const AccRouteWithChildren = AccRoute._addFileChildren(AccRouteChildren)

interface TodoIdRouteChildren {
  TodoIdCreateTaskRoute: typeof TodoIdCreateTaskRoute
}

const TodoIdRouteChildren: TodoIdRouteChildren = {
  TodoIdCreateTaskRoute: TodoIdCreateTaskRoute,
}

const TodoIdRouteWithChildren =
  TodoIdRoute._addFileChildren(TodoIdRouteChildren)

interface TodoRouteChildren {
  TodoIdRoute: typeof TodoIdRouteWithChildren
  TodoCreateFolderRoute: typeof TodoCreateFolderRoute
}

const TodoRouteChildren: TodoRouteChildren = {
  TodoIdRoute: TodoIdRouteWithChildren,
  TodoCreateFolderRoute: TodoCreateFolderRoute,
}

const TodoRouteWithChildren = TodoRoute._addFileChildren(TodoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccRoute: AccRouteWithChildren,
  TodoRoute: TodoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
