# Generated by Django 6.0.4 on 2026-04-28 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('description', models.TextField()),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
